version: '3.9'

services:
  user-db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: user_db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - user_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  post-db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: post_db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3309:3306"
    volumes:
      - post_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
      - "15673:15672"

  user-service:
    build:
      context: .
      dockerfile: ./user-service/Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      user-db:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  post-service:
    build:
      context: .
      dockerfile: ./post-service/Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      post-db:
        condition: service_healthy
      rabbitmq:
        condition: service_started

volumes:
  user_db_data:
  post_db_data:
